theme: minima
title: Learning how to use github-pages
author: CrazyTempo
email: xue63@me.com
description: > # this means to ignore newlines until "baseurl:"
  I start wrote this at 08/05/2020 14:24

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  rick8963 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
